### ISSUE TITLE
Better login method.

### ISSUE THREAD

**Issue by indrakaw** [RX14/discord-curses#17] opened 2016-05-18 01:56 UTC
Is there another way to login without input password into cli? e.g. `npm start my@email.com -p` then input password; password is hidden and can't be read in cli history.

**Comment by indrakaw** [comment] 2016-05-18 07:36
ping @RX14.

**Comment by RX14** [comment] 2016-05-18 17:05
Duplicate of #4

**Comment by RX14** [comment] 2016-05-18 17:06
No, it's not yet possible, and pinging me doesn't help when i'm not there.

I get pinged by the issue being opened, you don't need to mention me.

**Closed as completed by RX14** 2016-05-18 17:05 UTC
Labels: duplicate
